- name: checking template
  hosts: localhost
  tasks: 
  - name: loop of template
    ansible.builtin.debug: 
       msg: "{{ lookup('template', 'file1' ) }}"
    loop: 
    - name1
    - name2
    - name3   