- name: checking template
  hosts: localhost
  tasks: 
  - name: loop of template
    ansible.builtin.debug: 
       msg: "{{ lookup('file', 'file1') }}"
    loop: 
    - name1
    - name2
    - name3   