# - name: copy folder
#   ansible.builtin.template:
#      src: folder.xml
#      dest: /tmp/folder.xml

# - name: Create a jenkins job using basic authentication
#   community.general.jenkins_job:
#       config: "{{ lookup('file', '/tmp/folder.xml') }}" # java -jar jenkins-cli.jar -auth  -s http://184.72.135.255:8080/ get-job test1
#       name: "{{ item }}"
#       password: "{{ jenkins_pass }}"
#       url: http://184.72.135.255:8080
#       user: chaitu1812
#       state: absent

########-Method-2###################


- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
      config: "{{ lookup('template', 'folder.xml') }}" # java -jar jenkins-cli.jar -auth  -s http://184.72.135.255:8080/ get-job test1
      name: "{{ item }}"
      password: "{{ jenkins_pass }}"
      url: http://54.159.55.87:8080/
      user: chaitu1812

