- name: Jenkins Job Creation
  hosts: localhost
  tasks: 
  - name: Task to Create folders
    ansible.builtin.include_tasks: folders.yaml
    loop:
    - RoboshopCI

  - name: Calling include_taks file for sp-jobs
    ansible.builtin.include_tasks: sp-jobs.yaml
    vars: 
      # jobs_names: ['frontend','user','cart','payment','catalogue','dispatch','shipping']
      dir_name: "RoboshopCI"
    loop: 
    - { name: 'frontend' }
    - { name: 'user' }
    - { name: 'cart' }
    - { name: 'payment' }
    - { name: 'catalogue' }
    - { name: 'dispatch' }
    - { name: 'shippingg'}
  
