- name: loop1
  hosts: all
  become: yes
  vars:
      names:
        testuser1: 302
        testuser2: 302
        testuser3: 303 
        
  tasks:
  - name: dictionary loops
    ansible.builtin.debug:
        msg: "This is name-{{ item.key }} & rollno-{{ item.value }}"
    loop: "{{ dict_tag | dict2items }}"
    vars:
        dict_tag:
          testuser1: 302
          testuser2: 302
          testuser3: 303

  - name: dictionary loops
    ansible.builtin.debug:
        msg: "This is name-{{ item.key }} & rollno-{{ item.value }}"
    loop: "{{ names | dict2items }}"        
