- name: loop1
  hosts: all
  become: yes
  tasks:
  - name: hash loops
    ansible.builtin.debug:
        msg: "This name-{{ item.name }} & rollno-{{ rollno }}"
    loop:
    - { name: "testuser1", rollno: "301" }
    - { name: "testuser2", rollno: "302" }
    - { name: "testuser3", rollno: "303" }    