- name: Playbook to combine to json datas
  hosts: localhost
  vars:
  tasks:
  - name: Merge two json datas
    set_fact: "{{ lookup('file', './file1.json') | combine(lookup('file', './file1.json')) }}"
    