- name: Playbook to combine to json datas
  hosts: localhost
  vars:
  tasks:
  # - name: Merge two json datas
  #   set_fact: 
  #     hop: "{{ { 'name1': 'chaitu1', 'name4': 'goood' } | combine({'name2': 'chaitu2'}) }}"

  - name: print
    debug: 
      msg: "{{ lookup('file', './file1.json') }}"

  - name: print
    debug: 
      msg: "{{ (lookup('file', './file1.json') | from_json) | combine(lookup('file','./file2.json') | from_json)}}"    



    