- name: Playbook to combine to json datas
  hosts: localhost
  vars:
  tasks:
  - name: Merge two json datas
    set_fact: 
    hop: "{{ { 'name1': 'chaitu1' } | combine({'name2': 'chaitu2'}) }}"

  - name: print 
    var: hop 

    