- name: To Practice tags
  hosts: localhost
  tasks:
  - name: Task1
    debug:
      msg: This is task1

  - name: Shell-task1
    shell: exit 1
    ignore_errors: true 
    register: output

  - name: output debug
    debug: msg="{{ output }}"  

  # - name: fail the play if previous task is failed 
  #   debug: msg="the previous task if failed"
  #   when: output.failed is true    