- name: working split functions
  hosts: localhost
  vars:
   emails: ['chaitu@123','ram@gmail.com', 'haapy@gmail.com']
  tasks:
   - name: split1
     debug:
       msg: "{{ 'chaithanya is a bad boy' | split }}"
   - name: split2
     debug:
       msg: "{{ item | split('@') | first }}"
     loop: "{{ ['chaitu@123','ram@gmail.com', 'haapy@gmail.com'] }}"
   
   - name: split3
     debug:
       msg: "{{ emails }}"
  
